apiVersion: apps/v1
kind: Deployment
metadata:
  name: beancount-dep
  namespace: beancount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beancount
  template:
    metadata:
      labels:
        app: beancount
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-master-01
      containers:
        - name: fava
          image: yegle/fava:latest
          env:
            - name: BEANCOUNT_FILE
              value: "/data/beancount/main.beancount"
          volumeMounts:
            - mountPath: /data/beancount
              name: config-vol
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config-vol
          hostPath:
            path: /etc/beancount
