apiVersion: v1
kind: Secret
metadata:
  name: tls-<CHANGE_YOUR_DOMAIN>
  namespace: proxynet
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_TLS_CRT_STRING>
  tls.key: <BASE64_TLS_KEY_STRING>

# echo <<EOF | base64 -w 0
# base64 -w 0 ./tls.key
