# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# https://github.com/daeuniverse/dae/blob/main/.github/workflows/docker.yml

name: "Build dae Docker image"

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dae/docker"
      - ".github/workflows/dae-docker-build.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images to ghcr.io
        uses: docker/build-push-action@v4
        with:
          context: dae
          file: ./dae/docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64,linux/386
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dae:v0.6.0
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dae:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max